
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.monstersandgirls.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.monstersandgirls.block.YellowFlyAgaricHugeBlock;
import net.mcreator.monstersandgirls.block.Urn2Block;
import net.mcreator.monstersandgirls.block.Urn1Block;
import net.mcreator.monstersandgirls.block.SoullightBlock;
import net.mcreator.monstersandgirls.block.SoulWandererTrapdoorBlock;
import net.mcreator.monstersandgirls.block.SoulWandererStemBlock;
import net.mcreator.monstersandgirls.block.SoulWandererStairsBlock;
import net.mcreator.monstersandgirls.block.SoulWandererSlabsBlock;
import net.mcreator.monstersandgirls.block.SoulWandererPressurePlateBlock;
import net.mcreator.monstersandgirls.block.SoulWandererPlanksBlock;
import net.mcreator.monstersandgirls.block.SoulWandererMushroomBlock;
import net.mcreator.monstersandgirls.block.SoulWandererGateBlock;
import net.mcreator.monstersandgirls.block.SoulWandererFenceBlock;
import net.mcreator.monstersandgirls.block.SoulWandererDoorsBlock;
import net.mcreator.monstersandgirls.block.SoulWandererButtonBlock;
import net.mcreator.monstersandgirls.block.SoulWandererBlockBlock;
import net.mcreator.monstersandgirls.block.PottedSoulWandererBlock;
import net.mcreator.monstersandgirls.block.PottedMoltenFungusBlock;
import net.mcreator.monstersandgirls.block.PottedInkCapBlock;
import net.mcreator.monstersandgirls.block.PottedEnderPuffballBlock;
import net.mcreator.monstersandgirls.block.MoltenStemBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusTrapdoorBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusStairsBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusSlabsBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusPlateBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusPlanksBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusGateBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusFenceBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusDoorsBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusButtonBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusBlockBlock;
import net.mcreator.monstersandgirls.block.MoltenFungusBlock;
import net.mcreator.monstersandgirls.block.MandrakeBlock;
import net.mcreator.monstersandgirls.block.JarTerrariumBlock;
import net.mcreator.monstersandgirls.block.Inkcap3Block;
import net.mcreator.monstersandgirls.block.Inkcap2Block;
import net.mcreator.monstersandgirls.block.Inkcap1Block;
import net.mcreator.monstersandgirls.block.InkCapMushroomBlock;
import net.mcreator.monstersandgirls.block.HugeWarpedFungusBlock;
import net.mcreator.monstersandgirls.block.HugeToadstoolBlock;
import net.mcreator.monstersandgirls.block.HugeSoulWandererBlock;
import net.mcreator.monstersandgirls.block.HugePurpleBlock;
import net.mcreator.monstersandgirls.block.HugeMagmaFungusBlock;
import net.mcreator.monstersandgirls.block.HugeInkyCapBlock;
import net.mcreator.monstersandgirls.block.HugeInfernalMushroomBlock;
import net.mcreator.monstersandgirls.block.HugeGreenBlock;
import net.mcreator.monstersandgirls.block.HugeEnderPuffballBlock;
import net.mcreator.monstersandgirls.block.HugeCrimsonFungusBlock;
import net.mcreator.monstersandgirls.block.HugeBrownMushroomBlock;
import net.mcreator.monstersandgirls.block.GlowBerryBushUnlitBlock;
import net.mcreator.monstersandgirls.block.GlowBerryBushBlock;
import net.mcreator.monstersandgirls.block.EnderShroomlightBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballTrapdoorBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballStairsBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballSlabBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballPlateBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballPlanksBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballGateBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballFenceBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballDoorsBlock;
import net.mcreator.monstersandgirls.block.EnderPuffballButtonBlock;
import net.mcreator.monstersandgirls.block.EnderMushroomStemBlock;
import net.mcreator.monstersandgirls.block.EnderMossBlock;
import net.mcreator.monstersandgirls.block.EndPuffballBlock;
import net.mcreator.monstersandgirls.block.BlockofEnderPuffbalBlock;
import net.mcreator.monstersandgirls.MonstersAndGirlsMod;

public class MonstersAndGirlsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, MonstersAndGirlsMod.MODID);
	public static final RegistryObject<Block> HUGE_CRIMSON_FUNGUS = REGISTRY.register("huge_crimson_fungus", () -> new HugeCrimsonFungusBlock());
	public static final RegistryObject<Block> HUGE_PURPLE = REGISTRY.register("huge_purple", () -> new HugePurpleBlock());
	public static final RegistryObject<Block> HUGE_INKY_CAP = REGISTRY.register("huge_inky_cap", () -> new HugeInkyCapBlock());
	public static final RegistryObject<Block> HUGE_BROWN_MUSHROOM = REGISTRY.register("huge_brown_mushroom", () -> new HugeBrownMushroomBlock());
	public static final RegistryObject<Block> HUGE_TOADSTOOL = REGISTRY.register("huge_toadstool", () -> new HugeToadstoolBlock());
	public static final RegistryObject<Block> HUGE_INFERNAL_MUSHROOM = REGISTRY.register("huge_infernal_mushroom", () -> new HugeInfernalMushroomBlock());
	public static final RegistryObject<Block> YELLOW_FLY_AGARIC_HUGE = REGISTRY.register("yellow_fly_agaric_huge", () -> new YellowFlyAgaricHugeBlock());
	public static final RegistryObject<Block> HUGE_WARPED_FUNGUS = REGISTRY.register("huge_warped_fungus", () -> new HugeWarpedFungusBlock());
	public static final RegistryObject<Block> HUGE_GREEN = REGISTRY.register("huge_green", () -> new HugeGreenBlock());
	public static final RegistryObject<Block> HUGE_MAGMA_FUNGUS = REGISTRY.register("huge_magma_fungus", () -> new HugeMagmaFungusBlock());
	public static final RegistryObject<Block> HUGE_SOUL_WANDERER = REGISTRY.register("huge_soul_wanderer", () -> new HugeSoulWandererBlock());
	public static final RegistryObject<Block> HUGE_ENDER_PUFFBALL = REGISTRY.register("huge_ender_puffball", () -> new HugeEnderPuffballBlock());
	public static final RegistryObject<Block> JAR_TERRARIUM = REGISTRY.register("jar_terrarium", () -> new JarTerrariumBlock());
	public static final RegistryObject<Block> INKCAP_1 = REGISTRY.register("inkcap_1", () -> new Inkcap1Block());
	public static final RegistryObject<Block> INKCAP_2 = REGISTRY.register("inkcap_2", () -> new Inkcap2Block());
	public static final RegistryObject<Block> INKCAP_3 = REGISTRY.register("inkcap_3", () -> new Inkcap3Block());
	public static final RegistryObject<Block> INK_CAP_MUSHROOM = REGISTRY.register("ink_cap_mushroom", () -> new InkCapMushroomBlock());
	public static final RegistryObject<Block> BLOCKOF_ENDER_PUFFBAL = REGISTRY.register("blockof_ender_puffbal", () -> new BlockofEnderPuffbalBlock());
	public static final RegistryObject<Block> ENDER_SHROOMLIGHT = REGISTRY.register("ender_shroomlight", () -> new EnderShroomlightBlock());
	public static final RegistryObject<Block> ENDER_MUSHROOM_STEM = REGISTRY.register("ender_mushroom_stem", () -> new EnderMushroomStemBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_PLANKS = REGISTRY.register("ender_puffball_planks", () -> new EnderPuffballPlanksBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_STAIRS = REGISTRY.register("ender_puffball_stairs", () -> new EnderPuffballStairsBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_SLAB = REGISTRY.register("ender_puffball_slab", () -> new EnderPuffballSlabBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_FENCE = REGISTRY.register("ender_puffball_fence", () -> new EnderPuffballFenceBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_GATE = REGISTRY.register("ender_puffball_gate", () -> new EnderPuffballGateBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_PLATE = REGISTRY.register("ender_puffball_plate", () -> new EnderPuffballPlateBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_BUTTON = REGISTRY.register("ender_puffball_button", () -> new EnderPuffballButtonBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_DOORS = REGISTRY.register("ender_puffball_doors", () -> new EnderPuffballDoorsBlock());
	public static final RegistryObject<Block> ENDER_PUFFBALL_TRAPDOOR = REGISTRY.register("ender_puffball_trapdoor", () -> new EnderPuffballTrapdoorBlock());
	public static final RegistryObject<Block> END_PUFFBALL = REGISTRY.register("end_puffball", () -> new EndPuffballBlock());
	public static final RegistryObject<Block> ENDER_MOSS = REGISTRY.register("ender_moss", () -> new EnderMossBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_BLOCK = REGISTRY.register("soul_wanderer_block", () -> new SoulWandererBlockBlock());
	public static final RegistryObject<Block> SOULLIGHT = REGISTRY.register("soullight", () -> new SoullightBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_STEM = REGISTRY.register("soul_wanderer_stem", () -> new SoulWandererStemBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_PLANKS = REGISTRY.register("soul_wanderer_planks", () -> new SoulWandererPlanksBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_STAIRS = REGISTRY.register("soul_wanderer_stairs", () -> new SoulWandererStairsBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_SLABS = REGISTRY.register("soul_wanderer_slabs", () -> new SoulWandererSlabsBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_FENCE = REGISTRY.register("soul_wanderer_fence", () -> new SoulWandererFenceBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_GATE = REGISTRY.register("soul_wanderer_gate", () -> new SoulWandererGateBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_PRESSURE_PLATE = REGISTRY.register("soul_wanderer_pressure_plate", () -> new SoulWandererPressurePlateBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_BUTTON = REGISTRY.register("soul_wanderer_button", () -> new SoulWandererButtonBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_DOORS = REGISTRY.register("soul_wanderer_doors", () -> new SoulWandererDoorsBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_TRAPDOOR = REGISTRY.register("soul_wanderer_trapdoor", () -> new SoulWandererTrapdoorBlock());
	public static final RegistryObject<Block> SOUL_WANDERER_MUSHROOM = REGISTRY.register("soul_wanderer_mushroom", () -> new SoulWandererMushroomBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_BLOCK = REGISTRY.register("molten_fungus_block", () -> new MoltenFungusBlockBlock());
	public static final RegistryObject<Block> MOLTEN_STEM = REGISTRY.register("molten_stem", () -> new MoltenStemBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_PLANKS = REGISTRY.register("molten_fungus_planks", () -> new MoltenFungusPlanksBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_STAIRS = REGISTRY.register("molten_fungus_stairs", () -> new MoltenFungusStairsBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_SLABS = REGISTRY.register("molten_fungus_slabs", () -> new MoltenFungusSlabsBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_FENCE = REGISTRY.register("molten_fungus_fence", () -> new MoltenFungusFenceBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_GATE = REGISTRY.register("molten_fungus_gate", () -> new MoltenFungusGateBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_PLATE = REGISTRY.register("molten_fungus_plate", () -> new MoltenFungusPlateBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_BUTTON = REGISTRY.register("molten_fungus_button", () -> new MoltenFungusButtonBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_DOORS = REGISTRY.register("molten_fungus_doors", () -> new MoltenFungusDoorsBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS_TRAPDOOR = REGISTRY.register("molten_fungus_trapdoor", () -> new MoltenFungusTrapdoorBlock());
	public static final RegistryObject<Block> MOLTEN_FUNGUS = REGISTRY.register("molten_fungus", () -> new MoltenFungusBlock());
	public static final RegistryObject<Block> MANDRAKE = REGISTRY.register("mandrake", () -> new MandrakeBlock());
	public static final RegistryObject<Block> POTTED_SOUL_WANDERER = REGISTRY.register("potted_soul_wanderer", () -> new PottedSoulWandererBlock());
	public static final RegistryObject<Block> POTTED_MOLTEN_FUNGUS = REGISTRY.register("potted_molten_fungus", () -> new PottedMoltenFungusBlock());
	public static final RegistryObject<Block> POTTED_ENDER_PUFFBALL = REGISTRY.register("potted_ender_puffball", () -> new PottedEnderPuffballBlock());
	public static final RegistryObject<Block> POTTED_INK_CAP = REGISTRY.register("potted_ink_cap", () -> new PottedInkCapBlock());
	public static final RegistryObject<Block> GLOW_BERRY_BUSH = REGISTRY.register("glow_berry_bush", () -> new GlowBerryBushBlock());
	public static final RegistryObject<Block> GLOW_BERRY_BUSH_UNLIT = REGISTRY.register("glow_berry_bush_unlit", () -> new GlowBerryBushUnlitBlock());
	public static final RegistryObject<Block> URN_1 = REGISTRY.register("urn_1", () -> new Urn1Block());
	public static final RegistryObject<Block> URN_2 = REGISTRY.register("urn_2", () -> new Urn2Block());
}
